# pyproject.toml
# Purpose: Defines build system requirements and configures tools like Black, Flake8, Pytest.

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
# Configuration for the Black code formatter
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
# include = '\.pyi?$'
# exclude = '''
# /(
#     \.eggs         # exclude a few common directories in the
#   | \.git          # root of the project
#   | \.hg
#   | \.mypy_cache
#   | \.tox
#   | \.venv
#   | _build
#   | buck-out
#   | build
#   | dist
#   | node_modules
# )/
# '''

[tool.flake8]
# Configuration for Flake8 linter
max-line-length = 88
extend-ignore = [
    "E203", # Whitespace before ':' - conflicts with Black
    "W503", # Line break before binary operator - conflicts with Black
]
exclude = [
    ".git",
    "__pycache__",
    "docs/conf.py",
    "build",
    "dist",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "test-project/node_modules",
]
max-complexity = 10

[tool.pytest.ini_options]
# Configuration for Pytest test runner
minversion = "6.0"
addopts = "-ra -q --cov=dep_guardian --cov-report=term-missing" # Show summary info, quiet, add coverage
testpaths = [
    "tests", # Directory where tests are located
]
pythonpath = "." # Add project root to PYTHONPATH for imports

[tool.coverage.run]
branch = true
source = ["dep_guardian"]

[tool.coverage.report]
fail_under = 80 # Optional: Fail CI if coverage drops below 80%
show_missing = true